#line 2 "../../../cgdb/lib/tokenizer/cgdbhelplexer.cpp"

#line 4 "../../../cgdb/lib/tokenizer/cgdbhelplexer.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer cgdbhelp__create_buffer
#define yy_delete_buffer cgdbhelp__delete_buffer
#define yy_flex_debug cgdbhelp__flex_debug
#define yy_init_buffer cgdbhelp__init_buffer
#define yy_flush_buffer cgdbhelp__flush_buffer
#define yy_load_buffer_state cgdbhelp__load_buffer_state
#define yy_switch_to_buffer cgdbhelp__switch_to_buffer
#define yyin cgdbhelp_in
#define yyleng cgdbhelp_leng
#define yylex cgdbhelp_lex
#define yylineno cgdbhelp_lineno
#define yyout cgdbhelp_out
#define yyrestart cgdbhelp_restart
#define yytext cgdbhelp_text
#define yywrap cgdbhelp_wrap
#define yyalloc cgdbhelp_alloc
#define yyrealloc cgdbhelp_realloc
#define yyfree cgdbhelp_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE cgdbhelp_restart(cgdbhelp_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t cgdbhelp_leng;

extern FILE *cgdbhelp_in, *cgdbhelp_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up cgdbhelp_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up cgdbhelp_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via cgdbhelp_restart()), so that the user can continue scanning by
	 * just pointing cgdbhelp_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when cgdbhelp_text is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t cgdbhelp_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow cgdbhelp_wrap()'s to do buffer switches
 * instead of setting up a fresh cgdbhelp_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void cgdbhelp_restart (FILE *input_file  );
void cgdbhelp__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE cgdbhelp__create_buffer (FILE *file,int size  );
void cgdbhelp__delete_buffer (YY_BUFFER_STATE b  );
void cgdbhelp__flush_buffer (YY_BUFFER_STATE b  );
void cgdbhelp_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void cgdbhelp_pop_buffer_state (void );

static void cgdbhelp_ensure_buffer_stack (void );
static void cgdbhelp__load_buffer_state (void );
static void cgdbhelp__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER cgdbhelp__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE cgdbhelp__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE cgdbhelp__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE cgdbhelp__scan_bytes (yyconst char *bytes,yy_size_t len  );

void *cgdbhelp_alloc (yy_size_t  );
void *cgdbhelp_realloc (void *,yy_size_t  );
void cgdbhelp_free (void *  );

#define yy_new_buffer cgdbhelp__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        cgdbhelp_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            cgdbhelp__create_buffer(cgdbhelp_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        cgdbhelp_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            cgdbhelp__create_buffer(cgdbhelp_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define cgdbhelp_wrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *cgdbhelp_in = (FILE *) 0, *cgdbhelp_out = (FILE *) 0;

typedef int yy_state_type;

extern int cgdbhelp_lineno;

int cgdbhelp_lineno = 1;

extern char *cgdbhelp_text;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr cgdbhelp_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up cgdbhelp_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	cgdbhelp_leng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 29
#define YY_END_OF_BUFFER 30
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[205] =
    {   0,
        0,    0,   30,   28,   26,   23,   25,   28,   27,   27,
       22,   21,   24,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   27,   27,   22,   21,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   27,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    1,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   20,    0,    0,    0,    0,    0,    0,
        3,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    7,

        0,    0,    0,    0,    0,    0,    5,    0,    0,    0,
        0,    6,    0,    0,    0,    0,    0,    4,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    8,    0,
        0,    2,    0,   16,    0,    0,    0,    0,    9,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   18,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       19,    0,    0,    0,    0,    0,    0,    0,   11,   15,
        0,   17,   10,   14,    0,    0,    0,    0,    0,    0,

        0,   13,   12,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    1,    5,    1,
        1,    6,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        7,    1,    1,    1,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   13,   17,   18,   19,   20,   21,   22,
       13,   23,   24,   25,   26,   13,   27,   28,   29,   13,
        1,    1,    1,    1,   13,   30,   31,   32,   33,   34,

       35,   13,   36,   37,   38,   13,   39,   40,   41,   42,
       43,   44,   13,   45,   46,   47,   48,   13,   49,   50,
       51,   13,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[52] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    1,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2
    } ;

static yyconst flex_uint16_t yy_base[207] =
    {   0,
        0,   33,  377,  396,  396,  396,  369,   58,    0,    5,
      333,  273,  396,    0,    1,    4,    0,    4,    4,    5,
        4,   52,    0,    0,   20,  272,  208,   20,   53,   29,
       44,   48,   70,   63,   53,   66,   79,   93,   81,   98,
      101,   93,   89,  102,  104,   92,   96,   99,   98,  100,
      110,  101,  111,    0,  110,  116,  106,  120,  110,  129,
      202,  136,  124,  132,  144,  144,  197,  137,  140,  147,
      143,  137,  149,  396,  145,  144,  148,  143,  152,  149,
      396,  153,  150,  156,  174,  173,  168,  110,  184,  180,
      188,  189,  185,  188,   66,  180,  195,  188,  200,  396,

       56,  191,  203,  196,  202,  199,  396,   55,  211,  208,
      213,  396,  220,  217,  211,  219,  217,  396,  222,  228,
       54,  220,  231,   52,  236,   47,  237,  235,  396,  228,
      233,  396,   16,  396,  248,  239,  235,  250,  396,  248,
      251,  258,  282,  248,  268,  259,  265,  275,  278,  272,
      275,  275,  283,  287,  278,  284,  287,  295,   13,  295,
      289,  300,  308,  303,  307,  322,  320,  396,  316,  316,
      328,  325,   12,  314,  325,  327,  321,  320,  331,  333,
      396,   11,   10,  336,    9,    8,    7,  337,  396,  396,
      340,  396,  396,  396,  342,  345,  350,  341,  346,    6,

        4,  396,  396,  396,  393,    6
    } ;

static yyconst flex_int16_t yy_def[207] =
    {   0,
      205,  205,  204,  204,  204,  204,  204,  204,  206,  206,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  206,  206,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  206,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  206,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,

      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,

      204,  204,  204,    0,  204,  204
    } ;

static yyconst flex_uint16_t yy_nxt[448] =
    {   0,
        4,    5,    6,    7,    8,    4,    4,   24,  203,   10,
      202,  194,  193,  192,  190,  189,  181,  168,   25,   30,
      139,   29,   28,   32,   33,   34,   35,   31,   39,    8,
       40,   41,   10,    4,    5,    6,    7,    8,   11,   12,
       25,   30,   10,   29,   28,   32,   33,   34,   35,   31,
       39,  134,   44,   40,   41,   45,  132,   46,  129,  118,
      112,   36,    8,   37,   49,   10,   14,   15,   16,   17,
      107,   42,   43,   18,   44,   19,   38,   20,   45,   21,
       46,   22,   23,   47,   36,   48,   37,   49,   50,   14,
       15,   16,   17,   42,   43,   18,   51,   19,   38,   20,

       52,   21,   53,   22,   23,   47,   54,   48,   55,   58,
       50,   56,   57,   59,  100,   60,   61,   62,   51,   63,
       64,   65,   67,   52,   53,   66,   68,   69,   71,   54,
       70,   55,   58,   56,   57,   72,   59,   60,   61,   62,
       73,   63,   64,   75,   65,   67,   76,   66,   68,   77,
       69,   71,   70,   78,   84,   79,   87,   72,   82,   83,
       85,   86,   88,   73,   89,   90,   75,   91,   76,   80,
       92,   77,   93,   94,   95,   96,   78,   84,   79,   87,
       82,   83,   85,   86,   88,   97,   89,   90,   98,   91,
       99,   80,   92,  101,   93,   94,   95,   96,  102,  103,

      104,   81,  105,  106,  108,  109,   74,  110,   97,  111,
       98,  113,   99,  114,   27,  115,  101,  116,  117,  119,
      102,  120,  103,  104,  105,  106,  108,  121,  109,  110,
      122,  130,  111,  113,  123,  124,  114,  115,  125,  116,
      117,  126,  119,  120,  127,  128,  131,  133,  135,  121,
      136,  137,  138,  122,  130,  140,  123,  124,  141,  142,
      125,  143,  145,  126,  144,  146,  127,  128,  131,  151,
      133,  135,  136,  137,  138,  152,  153,   26,  140,   27,
      141,  142,  154,  155,  143,  145,  144,  156,  146,  147,
      148,  151,  157,  158,  159,  160,  149,  161,  152,  153,

      162,  150,  163,  164,  154,  155,  165,  166,  167,  156,
      169,  170,  147,  148,  157,  158,  159,  160,  149,  161,
      171,  172,  162,  150,  163,  164,  173,  174,  165,  166,
      167,  175,  169,  170,  176,  177,  178,  179,   26,  180,
      182,  183,  171,  172,  184,  185,  186,  187,  173,  174,
      188,  191,  195,  196,  175,  197,  176,  177,  178,  198,
      179,  180,  182,  183,  199,  200,  184,  185,  186,  187,
      201,   13,  188,  191,  195,  196,  204,  197,  204,  204,
      204,  198,  204,  204,  204,  204,  199,  200,  204,  204,
      204,  204,  201,    9,    9,    3,  204,  204,  204,  204,

      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204
    } ;

static yyconst flex_int16_t yy_chk[448] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,  206,  201,    1,
      200,  187,  186,  185,  183,  182,  173,  159,   10,   16,
      133,   15,   14,   18,   19,   20,   21,   17,   23,    1,
       25,   28,    1,    2,    2,    2,    2,    2,    2,    2,
       10,   16,    2,   15,   14,   18,   19,   20,   21,   17,
       23,  126,   30,   25,   28,   31,  124,   32,  121,  108,
      101,   22,    2,   22,   35,    2,    8,    8,    8,    8,
       95,   29,   29,    8,   30,    8,   22,    8,   31,    8,
       32,    8,    8,   33,   22,   34,   22,   35,   36,    8,
        8,    8,    8,   29,   29,    8,   37,    8,   22,    8,

       38,    8,   39,    8,    8,   33,   40,   34,   41,   44,
       36,   42,   43,   45,   88,   46,   47,   48,   37,   49,
       50,   51,   53,   38,   39,   52,   55,   56,   58,   40,
       57,   41,   44,   42,   43,   59,   45,   46,   47,   48,
       60,   49,   50,   62,   51,   53,   63,   52,   55,   64,
       56,   58,   57,   65,   70,   66,   73,   59,   68,   69,
       71,   72,   75,   60,   76,   77,   62,   78,   63,   66,
       79,   64,   80,   82,   83,   84,   65,   70,   66,   73,
       68,   69,   71,   72,   75,   85,   76,   77,   86,   78,
       87,   66,   79,   89,   80,   82,   83,   84,   90,   91,

       92,   67,   93,   94,   96,   97,   61,   98,   85,   99,
       86,  102,   87,  103,   27,  104,   89,  105,  106,  109,
       90,  110,   91,   92,   93,   94,   96,  111,   97,   98,
      113,  122,   99,  102,  114,  115,  103,  104,  116,  105,
      106,  117,  109,  110,  119,  120,  123,  125,  127,  111,
      128,  130,  131,  113,  122,  135,  114,  115,  136,  137,
      116,  138,  141,  117,  140,  142,  119,  120,  123,  144,
      125,  127,  128,  130,  131,  145,  145,   26,  135,   12,
      136,  137,  145,  146,  138,  141,  140,  147,  142,  143,
      143,  144,  148,  149,  150,  151,  143,  152,  145,  145,

      153,  143,  154,  155,  145,  146,  156,  157,  158,  147,
      160,  161,  143,  143,  148,  149,  150,  151,  143,  152,
      162,  163,  153,  143,  154,  155,  164,  165,  156,  157,
      158,  166,  160,  161,  167,  169,  170,  171,   11,  172,
      174,  175,  162,  163,  176,  177,  178,  179,  164,  165,
      180,  184,  188,  191,  166,  195,  167,  169,  170,  196,
      171,  172,  174,  175,  197,  198,  176,  177,  178,  179,
      199,    7,  180,  184,  188,  191,    3,  195,    0,    0,
        0,  196,    0,    0,    0,    0,  197,  198,    0,    0,
        0,    0,  199,  205,  205,  204,  204,  204,  204,  204,

      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  204
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int cgdbhelp__flex_debug;
int cgdbhelp__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *cgdbhelp_text;
#line 1 "../../../cgdb/lib/tokenizer/cgdbhelplexer.lpp"
#define YY_NO_INPUT 1
#line 12 "../../../cgdb/lib/tokenizer/cgdbhelplexer.lpp"

/* System Includes */
#include <stdio.h>
#include "tokenizer.h"

#line 662 "../../../cgdb/lib/tokenizer/cgdbhelplexer.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int cgdbhelp_lex_destroy (void );

int cgdbhelp_get_debug (void );

void cgdbhelp_set_debug (int debug_flag  );

YY_EXTRA_TYPE cgdbhelp_get_extra (void );

void cgdbhelp_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *cgdbhelp_get_in (void );

void cgdbhelp_set_in  (FILE * _in_str  );

FILE *cgdbhelp_get_out (void );

void cgdbhelp_set_out  (FILE * _out_str  );

yy_size_t cgdbhelp_get_leng (void );

char *cgdbhelp_get_text (void );

int cgdbhelp_get_lineno (void );

void cgdbhelp_set_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int cgdbhelp_wrap (void );
#else
extern int cgdbhelp_wrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( cgdbhelp_text, cgdbhelp_leng, 1, cgdbhelp_out )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( cgdbhelp_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( cgdbhelp_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, cgdbhelp_in))==0 && ferror(cgdbhelp_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(cgdbhelp_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int cgdbhelp_lex (void);

#define YY_DECL int cgdbhelp_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after cgdbhelp_text and cgdbhelp_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( cgdbhelp_leng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(cgdbhelp_text[cgdbhelp_leng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! cgdbhelp_in )
			cgdbhelp_in = stdin;

		if ( ! cgdbhelp_out )
			cgdbhelp_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			cgdbhelp_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				cgdbhelp__create_buffer(cgdbhelp_in,YY_BUF_SIZE );
		}

		cgdbhelp__load_buffer_state( );
		}

	{
#line 19 "../../../cgdb/lib/tokenizer/cgdbhelplexer.lpp"

#line 883 "../../../cgdb/lib/tokenizer/cgdbhelplexer.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of cgdbhelp_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 205 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 396 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 20 "../../../cgdb/lib/tokenizer/cgdbhelplexer.lpp"
{ return(TOKENIZER_KEYWORD); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 22 "../../../cgdb/lib/tokenizer/cgdbhelplexer.lpp"
{ return TOKENIZER_KEYWORD; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 23 "../../../cgdb/lib/tokenizer/cgdbhelplexer.lpp"
{ return TOKENIZER_TYPE; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 24 "../../../cgdb/lib/tokenizer/cgdbhelplexer.lpp"
{ return TOKENIZER_LITERAL; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 25 "../../../cgdb/lib/tokenizer/cgdbhelplexer.lpp"
{ return TOKENIZER_COMMENT; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 26 "../../../cgdb/lib/tokenizer/cgdbhelplexer.lpp"
{ return TOKENIZER_DIRECTIVE; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 27 "../../../cgdb/lib/tokenizer/cgdbhelplexer.lpp"
{ return TOKENIZER_TEXT; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 28 "../../../cgdb/lib/tokenizer/cgdbhelplexer.lpp"
{ return TOKENIZER_SEARCH; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 29 "../../../cgdb/lib/tokenizer/cgdbhelplexer.lpp"
{ return TOKENIZER_STATUS_BAR; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 30 "../../../cgdb/lib/tokenizer/cgdbhelplexer.lpp"
{ return TOKENIZER_EXECUTING_LINE_ARROW; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 31 "../../../cgdb/lib/tokenizer/cgdbhelplexer.lpp"
{ return TOKENIZER_SELECTED_LINE_ARROW; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 32 "../../../cgdb/lib/tokenizer/cgdbhelplexer.lpp"
{ return TOKENIZER_EXECUTING_LINE_HIGHLIGHT; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 33 "../../../cgdb/lib/tokenizer/cgdbhelplexer.lpp"
{ return TOKENIZER_SELECTED_LINE_HIGHLIGHT; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 34 "../../../cgdb/lib/tokenizer/cgdbhelplexer.lpp"
{ return TOKENIZER_EXECUTING_LINE_BLOCK; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 35 "../../../cgdb/lib/tokenizer/cgdbhelplexer.lpp"
{ return TOKENIZER_SELECTED_LINE_BLOCK; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 36 "../../../cgdb/lib/tokenizer/cgdbhelplexer.lpp"
{ return TOKENIZER_ENABLED_BREAKPOINT; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 37 "../../../cgdb/lib/tokenizer/cgdbhelplexer.lpp"
{ return TOKENIZER_DISABLED_BREAKPOINT; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 38 "../../../cgdb/lib/tokenizer/cgdbhelplexer.lpp"
{ return TOKENIZER_SELECTED_LINE_NUMBER; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 39 "../../../cgdb/lib/tokenizer/cgdbhelplexer.lpp"
{ return TOKENIZER_SCROLL_MODE_STATUS; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 40 "../../../cgdb/lib/tokenizer/cgdbhelplexer.lpp"
{ return TOKENIZER_LOGO; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 42 "../../../cgdb/lib/tokenizer/cgdbhelplexer.lpp"
{ return(TOKENIZER_COMMENT); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 43 "../../../cgdb/lib/tokenizer/cgdbhelplexer.lpp"
{ return(TOKENIZER_COMMENT); }
	YY_BREAK
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 45 "../../../cgdb/lib/tokenizer/cgdbhelplexer.lpp"
{ return(TOKENIZER_NEWLINE); }
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 46 "../../../cgdb/lib/tokenizer/cgdbhelplexer.lpp"
{ return(TOKENIZER_NEWLINE); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 47 "../../../cgdb/lib/tokenizer/cgdbhelplexer.lpp"
{ return(TOKENIZER_NEWLINE); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 48 "../../../cgdb/lib/tokenizer/cgdbhelplexer.lpp"
{ return(TOKENIZER_TEXT);    }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 49 "../../../cgdb/lib/tokenizer/cgdbhelplexer.lpp"
{ return(TOKENIZER_TEXT); 	 }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 50 "../../../cgdb/lib/tokenizer/cgdbhelplexer.lpp"
{ return(TOKENIZER_TEXT);    }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 51 "../../../cgdb/lib/tokenizer/cgdbhelplexer.lpp"
ECHO;
	YY_BREAK
#line 1088 "../../../cgdb/lib/tokenizer/cgdbhelplexer.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed cgdbhelp_in at a new source and called
			 * cgdbhelp_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = cgdbhelp_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( cgdbhelp_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * cgdbhelp_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of cgdbhelp_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					cgdbhelp_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			cgdbhelp_restart(cgdbhelp_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) cgdbhelp_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 205 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 205 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 204);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					cgdbhelp_restart(cgdbhelp_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( cgdbhelp_wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve cgdbhelp_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void cgdbhelp_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        cgdbhelp_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            cgdbhelp__create_buffer(cgdbhelp_in,YY_BUF_SIZE );
	}

	cgdbhelp__init_buffer(YY_CURRENT_BUFFER,input_file );
	cgdbhelp__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void cgdbhelp__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		cgdbhelp_pop_buffer_state();
	 *		cgdbhelp_push_buffer_state(new_buffer);
     */
	cgdbhelp_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	cgdbhelp__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (cgdbhelp_wrap()) processing, but the only time this flag
	 * is looked at is after cgdbhelp_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void cgdbhelp__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	cgdbhelp_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE cgdbhelp__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) cgdbhelp_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in cgdbhelp__create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) cgdbhelp_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in cgdbhelp__create_buffer()" );

	b->yy_is_our_buffer = 1;

	cgdbhelp__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with cgdbhelp__create_buffer()
 * 
 */
    void cgdbhelp__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		cgdbhelp_free((void *) b->yy_ch_buf  );

	cgdbhelp_free((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a cgdbhelp_restart() or at EOF.
 */
    static void cgdbhelp__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	cgdbhelp__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then cgdbhelp__init_buffer was _probably_
     * called from cgdbhelp_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void cgdbhelp__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		cgdbhelp__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void cgdbhelp_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	cgdbhelp_ensure_buffer_stack();

	/* This block is copied from cgdbhelp__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from cgdbhelp__switch_to_buffer. */
	cgdbhelp__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void cgdbhelp_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	cgdbhelp__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		cgdbhelp__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void cgdbhelp_ensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)cgdbhelp_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in cgdbhelp_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)cgdbhelp_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in cgdbhelp_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE cgdbhelp__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) cgdbhelp_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in cgdbhelp__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	cgdbhelp__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to cgdbhelp_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       cgdbhelp__scan_bytes() instead.
 */
YY_BUFFER_STATE cgdbhelp__scan_string (yyconst char * yystr )
{
    
	return cgdbhelp__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to cgdbhelp_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE cgdbhelp__scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) cgdbhelp_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in cgdbhelp__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = cgdbhelp__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in cgdbhelp__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up cgdbhelp_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		cgdbhelp_text[cgdbhelp_leng] = (yy_hold_char); \
		(yy_c_buf_p) = cgdbhelp_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		cgdbhelp_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int cgdbhelp_get_lineno  (void)
{
        
    return cgdbhelp_lineno;
}

/** Get the input stream.
 * 
 */
FILE *cgdbhelp_get_in  (void)
{
        return cgdbhelp_in;
}

/** Get the output stream.
 * 
 */
FILE *cgdbhelp_get_out  (void)
{
        return cgdbhelp_out;
}

/** Get the length of the current token.
 * 
 */
yy_size_t cgdbhelp_get_leng  (void)
{
        return cgdbhelp_leng;
}

/** Get the current token.
 * 
 */

char *cgdbhelp_get_text  (void)
{
        return cgdbhelp_text;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void cgdbhelp_set_lineno (int  _line_number )
{
    
    cgdbhelp_lineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see cgdbhelp__switch_to_buffer
 */
void cgdbhelp_set_in (FILE *  _in_str )
{
        cgdbhelp_in = _in_str ;
}

void cgdbhelp_set_out (FILE *  _out_str )
{
        cgdbhelp_out = _out_str ;
}

int cgdbhelp_get_debug  (void)
{
        return cgdbhelp__flex_debug;
}

void cgdbhelp_set_debug (int  _bdebug )
{
        cgdbhelp__flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from cgdbhelp_lex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    cgdbhelp_in = stdin;
    cgdbhelp_out = stdout;
#else
    cgdbhelp_in = (FILE *) 0;
    cgdbhelp_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * cgdbhelp_lex_init()
     */
    return 0;
}

/* cgdbhelp_lex_destroy is for both reentrant and non-reentrant scanners. */
int cgdbhelp_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		cgdbhelp__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		cgdbhelp_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	cgdbhelp_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * cgdbhelp_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *cgdbhelp_alloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *cgdbhelp_realloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void cgdbhelp_free (void * ptr )
{
			free( (char *) ptr );	/* see cgdbhelp_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 51 "../../../cgdb/lib/tokenizer/cgdbhelplexer.lpp"



