#line 2 "golexer.c"

#line 4 "golexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer go__create_buffer
#define yy_delete_buffer go__delete_buffer
#define yy_flex_debug go__flex_debug
#define yy_init_buffer go__init_buffer
#define yy_flush_buffer go__flush_buffer
#define yy_load_buffer_state go__load_buffer_state
#define yy_switch_to_buffer go__switch_to_buffer
#define yyin go_in
#define yyleng go_leng
#define yylex go_lex
#define yylineno go_lineno
#define yyout go_out
#define yyrestart go_restart
#define yytext go_text
#define yywrap go_wrap
#define yyalloc go_alloc
#define yyrealloc go_realloc
#define yyfree go_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE go_restart(go_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int go_leng;

extern FILE *go_in, *go_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up go_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up go_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via go_restart()), so that the user can continue scanning by
	 * just pointing go_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when go_text is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int go_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow go_wrap()'s to do buffer switches
 * instead of setting up a fresh go_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void go_restart (FILE *input_file  );
void go__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE go__create_buffer (FILE *file,int size  );
void go__delete_buffer (YY_BUFFER_STATE b  );
void go__flush_buffer (YY_BUFFER_STATE b  );
void go_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void go_pop_buffer_state (void );

static void go_ensure_buffer_stack (void );
static void go__load_buffer_state (void );
static void go__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER go__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE go__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE go__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE go__scan_bytes (yyconst char *bytes,int len  );

void *go_alloc (yy_size_t  );
void *go_realloc (void *,yy_size_t  );
void go_free (void *  );

#define yy_new_buffer go__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        go_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            go__create_buffer(go_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        go_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            go__create_buffer(go_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *go_in = (FILE *) 0, *go_out = (FILE *) 0;

typedef int yy_state_type;

extern int go_lineno;

int go_lineno = 1;

extern char *go_text;
#define yytext_ptr go_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up go_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	go_leng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 87
#define YY_END_OF_BUFFER 88
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[241] =
    {   0,
        0,    0,   47,   47,   55,   55,   88,   86,   84,   81,
       83,   54,   86,   86,   86,   60,   60,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   47,   49,   50,   48,   55,   56,   57,   59,
       87,   82,    0,    0,   76,   46,   53,    0,   60,    0,
       77,   61,   62,    0,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   34,   36,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   47,   51,   48,   48,   52,   55,
        0,   58,   79,    0,   79,   78,   53,   76,    0,   76,

       63,   66,   64,   68,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   33,   85,   85,   85,    3,
       22,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   45,   80,   67,   65,   69,   70,    1,   85,   16,
       25,   23,   85,   85,   85,   85,   85,   30,   85,   85,
       85,   20,   35,   85,   85,   85,   85,    8,   85,   85,
       85,   85,   17,   85,   85,   85,   85,   43,   44,    2,
       71,   74,   72,   24,   85,   26,   85,   85,   29,   85,
       32,   85,   85,    9,   10,   11,   85,   85,   39,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   75,   73,

       85,   85,   85,   85,   85,   85,   37,   85,   85,   40,
       41,   18,   19,   42,    5,    6,    7,   85,   85,   85,
       28,   85,   12,   13,   85,   38,    4,   85,   85,   27,
       85,   85,   85,   14,   85,   21,   15,   85,   31,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    1,    1,    1,    1,    6,    1,
        1,    7,    8,    1,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   16,   18,   16,    1,    1,    1,
        1,    1,    1,    1,   19,   19,   19,   19,   20,   21,
       22,   22,   22,   22,   22,   23,   22,   22,   22,   22,
       22,   22,   22,   22,   24,   22,   22,   22,   22,   22,
        1,   25,    1,    1,   19,    1,   26,   27,   28,   29,

       30,   31,   32,   33,   34,   22,   35,   36,   37,   38,
       39,   40,   22,   41,   42,   43,   44,   45,   46,   47,
       48,   22,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[49] =
    {   0,
        1,    1,    2,    3,    4,    1,    5,    6,    1,    1,
        7,    7,    7,    7,    7,    7,    7,    7,    8,    8,
        9,   10,   10,   10,    1,    8,    8,    8,    8,    8,
        9,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10
    } ;

static yyconst flex_int16_t yy_base[255] =
    {   0,
        0,    0,   46,   48,   53,   56,  318,  916,  916,  916,
      304,  916,  281,    0,   55,   73,  257,  110,  118,   66,
       71,   27,   28,   32,  106,  112,  122,  132,  126,   67,
      143,  142,    0,  916,  295,   67,  264,  916,  282,  916,
      272,  916,  265,  263,  119,  916,    0,  121,  210,  244,
      916,  162,   47,    0,    0,  148,  153,  163,  164,  174,
      169,  182,  187,  190,  198,  201,  202,  206,  212,  217,
      222,  225,  235,  239,  243,  247,  255,  261,  260,  271,
      272,  282,  276,  286,    0,  916,   88,  106,  916,  223,
      231,  916,  916,  227,  219,  916,    0,  308,  216,  201,

      131,  916,  191,  308,  301,  307,  306,  320,  319,  323,
      331,  339,  336,  347,  355,  351,  363,  359,  367,  404,
      371,  385,  391,  396,  408,  412,  420,  388,  428,  432,
      407,  424,  916,  916,  916,  451,  236,  438,  443,  442,
      453,  457,  461,  465,  473,  476,  477,  487,  488,  493,
      499,  498,  504,  509,  183,  184,  173,    0,  510,  527,
      524,  521,  532,  542,  538,  546,  550,  554,  558,  591,
      155,  916,  256,  571,  574,  575,  579,  589,  585,  599,
      595,  625,  605,    0,    0,    0,  610,  613,  621,  629,
      633,  639,  643,  655,  161,  151,  131,  654,  916,  916,

      651,  665,  669,  666,  128,  103,  677,  685,  689,  681,
      693,  697,  701,  705,    0,    0,    0,  709,  735,  721,
      715,  720,    0,    0,  736,  731,  732,   98,   87,  746,
      747,  751,   82,    0,  757,  761,    0,  771,  767,  916,
      819,  829,  839,   72,  843,  853,  863,  873,  883,  893,
      897,  901,  902,  905
    } ;

static yyconst flex_int16_t yy_def[255] =
    {   0,
      240,    1,  241,  241,  242,  242,  240,  240,  240,  240,
      240,  240,  243,  244,  240,  240,   16,  245,  245,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,  246,  240,  240,  247,  248,  240,  240,  240,
      248,  240,  240,  249,  244,  240,  250,  251,   16,  252,
      240,  240,  240,  253,  254,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,  246,  240,  247,  247,  240,  248,
      248,  240,  240,  240,  240,  240,  250,  251,  252,  252,

      240,  240,  240,  253,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,  240,  240,  240,  240,  240,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,  254,  254,  254,  254,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,  120,
      240,  240,  240,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,  254,  254,  254,   19,   19,   19,   19,
       19,   19,   19,   19,  254,  254,  254,   19,  240,  240,

       19,   19,   19,   19,  254,  254,   19,   19,   19,   19,
       19,   19,   19,   19,  254,  254,  254,   19,   19,   19,
       19,   19,  254,  254,   19,   19,   19,  254,  254,   19,
       19,   19,  254,  254,   19,   19,  254,   19,   19,    0,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240
    } ;

static yyconst flex_int16_t yy_nxt[965] =
    {   0,
        8,    9,   10,   11,   12,   13,    8,    8,   14,   15,
       16,   17,   17,   17,   17,   17,   17,   17,   18,   18,
       18,   18,   18,   18,    8,   18,   19,   20,   21,   22,
       23,   24,   18,   25,   18,   18,   26,   18,   18,   27,
       28,   29,   30,   31,   32,   18,   18,   18,   34,   35,
       34,   35,   36,   65,   36,   38,   39,   40,   38,   39,
       40,   46,   64,   66,   47,   56,   67,   56,   56,  103,
       69,   68,   56,   88,   56,   56,   89,   41,   45,   56,
       41,   48,  103,   49,   49,   49,   49,   49,   49,   49,
       49,   60,   50,   51,  240,   52,   53,  240,   61,  237,

       63,  234,   50,   51,   62,   56,   56,   81,   52,   56,
      233,   56,   88,   56,   82,   89,   53,  224,   56,   54,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   70,   73,   50,   96,
      223,   51,   71,   72,   56,  217,   56,   74,   50,   96,
       56,   51,   56,   56,  134,   78,   57,   75,   58,   56,
       56,   76,   56,  216,   56,   59,   56,   84,   79,   56,
       56,   80,   56,   56,  134,   77,   83,  215,  199,   56,
       56,   56,   56,   56,  101,  102,   56,  186,   56,   56,
       56,  105,  106,   56,  109,   56,  185,  101,  199,  184,

       56,   56,   56,   56,   56,  102,  107,   56,  240,   56,
       56,   56,   56,  135,   56,  108,   56,  112,  110,  111,
       56,   56,   56,  240,  133,   56,  135,   56,   56,   56,
       56,  113,  133,  114,   56,   90,   56,   56,   56,  115,
       56,   56,  116,  117,   56,   56,   56,   91,   56,   56,
       56,   99,   56,   56,  118,   56,  240,   56,  173,   56,
       56,  119,   56,   56,   56,   56,  122,  120,   95,   56,
       93,  173,   56,   56,  121,   56,   90,   56,  200,   56,
      123,   56,   56,   56,   92,   56,   56,   56,   91,  124,
       56,  200,  125,   56,   56,   56,  126,   86,   56,   56,

      127,   56,   56,  240,  128,   44,   42,   56,   56,   56,
       56,   56,   56,  131,   56,  129,   56,  240,   56,   56,
       56,  130,   56,   56,   56,  240,  132,   50,   51,   56,
      136,  137,  139,   56,  240,  140,  138,   50,   51,   56,
      240,   56,  240,  136,   56,   56,   56,   56,   56,  141,
      240,  137,  240,   56,   56,  240,  142,   56,   56,   56,
       56,   56,  143,   56,  146,  148,   56,   56,  147,   56,
       56,   56,  144,  145,   56,  240,   56,   56,   56,   56,
      151,  240,  149,   56,  240,   56,   56,   56,  150,   56,
      152,   56,  240,   56,   56,   56,  240,  153,   56,   56,

      240,   56,   56,   56,  240,  154,   56,   56,  240,   56,
       56,   56,  240,  240,   56,  155,  240,  156,   56,  160,
      157,  158,  161,   56,  240,   56,   56,  240,   56,   56,
      167,   56,   56,  159,   56,   56,   56,  163,   56,  162,
      240,  164,   56,   56,   56,   56,   56,   56,   56,  170,
       56,   56,   56,  165,   56,   56,  240,  168,   56,   56,
       56,  169,   56,  166,   56,  240,   56,   56,   56,  240,
       56,   56,   56,  171,  172,   56,   56,  174,   56,   56,
       56,   56,   56,   56,  240,   56,  171,  240,  240,   56,
       56,   56,  240,   56,  172,   56,  175,   56,  240,   56,

       56,   56,  240,   56,   56,   56,  177,  176,   56,  240,
      240,   56,   56,   56,   56,   56,   56,  179,  240,  178,
       56,  240,  181,   56,   56,   56,   56,   56,   56,  240,
      180,   56,  240,   56,   56,   56,   56,   56,   56,   56,
       56,  182,   56,  240,   56,   56,   56,   56,   56,  183,
      187,   56,  188,  189,  240,  240,   56,   56,  240,   56,
      240,  190,   56,  240,   56,   56,  240,   56,   56,  191,
       56,   56,   56,  193,   56,  192,   56,  194,   56,   56,
       56,  240,   56,  240,   56,   56,   56,  240,   56,   56,
       56,  240,   56,   56,   56,  240,   56,   56,   56,  240,

      240,   56,  195,  201,  196,   56,  240,  197,   55,   56,
      240,   56,   56,   56,   56,   56,  202,   56,   56,   56,
       56,   56,   56,   56,  203,   56,   56,   56,  240,   56,
      198,  204,   56,   56,  240,   56,   56,   56,  205,   56,
      208,  206,   56,   56,  209,   56,   56,  207,   56,  240,
       56,   56,   56,   56,  240,  240,  240,   56,  240,   56,
       56,   56,  240,   56,  240,   56,  210,   56,   56,   56,
      212,   56,   56,   56,  240,  211,   56,   56,  240,   56,
       56,   56,  240,   56,  240,  213,   56,  214,  240,   56,
       56,   56,   56,   56,   56,   56,  218,  219,   56,  240,

      240,   56,   56,   56,   56,   56,  222,   56,  220,   56,
      225,  221,   56,   56,  240,   56,   56,   56,  226,   56,
      240,   56,  240,   56,   56,   56,  240,   56,   56,   56,
      240,   56,   56,   56,  240,   56,   56,   56,  240,   56,
       56,   56,  240,   56,   56,   56,  228,   56,   56,  227,
      230,  229,   56,   56,  240,   56,   56,  240,  231,   56,
       56,   56,   56,  232,  240,  240,  240,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,  240,   56,   56,
      236,  240,   56,   56,   56,   56,   56,   56,  238,   56,
      235,   56,  240,   56,   56,   56,  240,   56,   56,   56,

      240,   56,  240,  239,   56,   56,  240,   56,   56,   56,
      240,   56,  240,  240,   56,  240,  240,  240,   56,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   37,
       37,   37,   37,   37,   37,   37,   37,   37,   37,   43,
      240,   43,   43,   43,   43,   43,   43,   43,   43,   56,
       56,   56,   56,   85,  240,  240,   85,  240,   85,   85,
       85,   85,   85,   87,  240,  240,   87,   87,   87,   87,
       87,   87,   87,   90,  240,  240,  240,   90,   90,   90,
       90,   90,   90,   94,  240,   94,   94,   94,   94,   94,
       94,   94,   94,   97,  240,  240,   97,   97,   97,   97,

       97,   97,   97,   98,  240,   98,  100,  100,  104,  104,
      104,   55,   55,   55,   55,    7,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240
    } ;

static yyconst flex_int16_t yy_chk[965] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    3,
        4,    4,    3,   23,    4,    5,    5,    5,    6,    6,
        6,   15,   22,   23,   15,   22,   23,   22,   23,   53,
       24,   23,   24,   36,   22,   23,   36,    5,  244,   24,
        6,   16,   53,   16,   16,   16,   16,   16,   16,   16,
       16,   20,   16,   16,   87,   16,   16,   87,   20,  233,

       21,  229,   16,   16,   20,   30,   20,   30,   16,   21,
      228,   21,   88,   20,   30,   88,   16,  206,   21,   16,
       18,   18,   18,   18,   18,   18,   18,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   25,   26,   45,   45,
      205,   48,   25,   25,   25,  197,   25,   27,   45,   45,
       26,   48,   26,   25,  101,   29,   19,   28,   19,   26,
       27,   28,   27,  196,   29,   19,   29,   32,   29,   27,
       28,   29,   28,   29,  101,   28,   31,  195,  171,   28,
       32,   31,   32,   31,   52,   52,   56,  157,   56,   32,
       31,   57,   58,   57,   61,   56,  156,   52,  171,  155,

       57,   58,   59,   58,   59,   52,   59,   61,  100,   61,
       58,   59,   60,  103,   60,   60,   61,   63,   62,   62,
       62,   60,   62,   99,   95,   63,  103,   63,   64,   62,
       64,   64,   94,   65,   63,   91,   65,   64,   65,   66,
       67,   66,   67,   68,   68,   65,   68,   90,   66,   67,
       69,   50,   69,   68,   69,   70,   49,   70,  137,   69,
       71,   71,   71,   72,   70,   72,   74,   72,   44,   71,
       43,  137,   72,   73,   73,   73,   41,   74,  173,   74,
       75,   75,   73,   75,   39,   76,   74,   76,   37,   76,
       75,  173,   77,   77,   76,   77,   78,   35,   79,   78,

       79,   78,   77,   17,   80,   13,   11,   79,   78,   80,
       81,   80,   81,   83,   83,   81,   83,    7,   80,   81,
       82,   82,   82,   83,   84,    0,   84,   98,   98,   82,
      104,  104,  106,   84,    0,  107,  105,   98,   98,  105,
        0,  105,    0,  104,  107,  106,  107,  106,  105,  108,
        0,  104,    0,  107,  106,    0,  109,  109,  108,  109,
      108,  110,  110,  110,  112,  113,  109,  108,  112,  111,
      110,  111,  111,  111,  113,    0,  113,  112,  111,  112,
      115,    0,  114,  113,    0,  114,  112,  114,  114,  116,
      117,  116,    0,  115,  114,  115,    0,  118,  116,  118,

        0,  117,  115,  117,    0,  119,  118,  119,    0,  121,
      117,  121,    0,    0,  119,  120,    0,  120,  121,  122,
      120,  120,  123,  122,    0,  122,  128,    0,  128,  123,
      128,  123,  122,  120,  124,  128,  124,  125,  123,  124,
        0,  126,  120,  124,  120,  131,  125,  131,  125,  131,
      126,  120,  126,  127,  131,  125,    0,  129,  127,  126,
      127,  130,  132,  127,  132,    0,  129,  127,  129,    0,
      130,  132,  130,  136,  136,  129,  138,  139,  138,  130,
      140,  139,  140,  139,    0,  138,  136,    0,    0,  140,
      139,  141,    0,  141,  136,  142,  143,  142,    0,  143,

      141,  143,    0,  144,  142,  144,  145,  144,  143,    0,
        0,  145,  144,  145,  146,  147,  146,  147,    0,  146,
      145,    0,  150,  146,  147,  148,  149,  148,  149,    0,
      149,  150,    0,  150,  148,  149,  152,  151,  152,  151,
      150,  151,  153,    0,  153,  152,  151,  154,  159,  154,
      159,  153,  160,  161,    0,    0,  154,  159,    0,  162,
        0,  162,  161,    0,  161,  160,    0,  160,  162,  164,
      163,  161,  163,  166,  160,  165,  165,  167,  165,  163,
      164,    0,  164,    0,  166,  165,  166,    0,  167,  164,
      167,    0,  168,  166,  168,    0,  169,  167,  169,    0,

        0,  168,  170,  175,  170,  169,    0,  170,  170,  174,
        0,  174,  175,  176,  175,  176,  177,  177,  174,  177,
      170,  175,  176,  179,  178,  179,  177,  178,    0,  178,
      170,  180,  179,  181,    0,  181,  178,  180,  182,  180,
      187,  182,  181,  183,  188,  183,  180,  183,  187,    0,
      187,  188,  183,  188,    0,    0,    0,  187,    0,  189,
      188,  189,    0,  182,    0,  182,  190,  190,  189,  190,
      192,  191,  182,  191,    0,  191,  190,  192,    0,  192,
      191,  193,    0,  193,    0,  193,  192,  194,    0,  201,
      193,  201,  198,  194,  198,  194,  198,  201,  201,    0,

        0,  198,  194,  202,  204,  202,  204,  203,  202,  203,
      208,  203,  202,  204,    0,  207,  203,  207,  209,  210,
        0,  210,    0,  208,  207,  208,    0,  209,  210,  209,
        0,  211,  208,  211,    0,  212,  209,  212,    0,  213,
      211,  213,    0,  214,  212,  214,  219,  218,  213,  218,
      220,  219,  214,  221,    0,  221,  218,    0,  222,  220,
      222,  220,  221,  225,    0,    0,    0,  222,  220,  226,
      227,  226,  227,  219,  225,  219,  225,    0,  226,  227,
      232,    0,  219,  225,  230,  231,  230,  231,  235,  232,
      231,  232,    0,  230,  231,  235,    0,  235,  232,  236,

        0,  236,    0,  238,  235,  239,    0,  239,  236,  238,
        0,  238,    0,    0,  239,    0,    0,    0,  238,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  243,
        0,  243,  243,  243,  243,  243,  243,  243,  243,  245,
      245,  245,  245,  246,    0,    0,  246,    0,  246,  246,
      246,  246,  246,  247,    0,    0,  247,  247,  247,  247,
      247,  247,  247,  248,    0,    0,    0,  248,  248,  248,
      248,  248,  248,  249,    0,  249,  249,  249,  249,  249,
      249,  249,  249,  250,    0,    0,  250,  250,  250,  250,

      250,  250,  250,  251,    0,  251,  252,  252,  253,  253,
      253,  254,  254,  254,  254,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240,  240,  240,  240,  240,  240,  240,
      240,  240,  240,  240
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int go__flex_debug;
int go__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *go_text;
#line 1 "golexer.l"
#line 11 "golexer.l"

#include <stdio.h>
#include "tokenizer.h"


#line 777 "golexer.c"

#define INITIAL 0
#define comment 1
#define string_literal 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int go_lex_destroy (void );

int go_get_debug (void );

void go_set_debug (int debug_flag  );

YY_EXTRA_TYPE go_get_extra (void );

void go_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *go_get_in (void );

void go_set_in  (FILE * in_str  );

FILE *go_get_out (void );

void go_set_out  (FILE * out_str  );

int go_get_leng (void );

char *go_get_text (void );

int go_get_lineno (void );

void go_set_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int go_wrap (void );
#else
extern int go_wrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( go_text, go_leng, 1, go_out )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( go_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( go_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, go_in))==0 && ferror(go_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(go_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int go_lex (void);

#define YY_DECL int go_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after go_text and go_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 19 "golexer.l"

#line 968 "golexer.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! go_in )
			go_in = stdin;

		if ( ! go_out )
			go_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			go_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				go__create_buffer(go_in,YY_BUF_SIZE );
		}

		go__load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of go_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 241 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 916 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 20 "golexer.l"
{ return(TOKENIZER_TYPE); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 21 "golexer.l"
{ return(TOKENIZER_TYPE); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 22 "golexer.l"
{ return(TOKENIZER_TYPE); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 23 "golexer.l"
{ return(TOKENIZER_TYPE); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 24 "golexer.l"
{ return(TOKENIZER_TYPE); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 25 "golexer.l"
{ return(TOKENIZER_TYPE); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 26 "golexer.l"
{ return(TOKENIZER_TYPE); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 27 "golexer.l"
{ return(TOKENIZER_TYPE); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 28 "golexer.l"
{ return(TOKENIZER_TYPE); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 29 "golexer.l"
{ return(TOKENIZER_TYPE); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 30 "golexer.l"
{ return(TOKENIZER_TYPE); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 31 "golexer.l"
{ return(TOKENIZER_TYPE); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 32 "golexer.l"
{ return(TOKENIZER_TYPE); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 33 "golexer.l"
{ return(TOKENIZER_TYPE); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 34 "golexer.l"
{ return(TOKENIZER_TYPE); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 35 "golexer.l"
{ return(TOKENIZER_TYPE); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 36 "golexer.l"
{ return(TOKENIZER_TYPE); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 37 "golexer.l"
{ return(TOKENIZER_TYPE); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 38 "golexer.l"
{ return(TOKENIZER_TYPE); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 39 "golexer.l"
{ return(TOKENIZER_TYPE); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 40 "golexer.l"
{ return(TOKENIZER_TYPE); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 41 "golexer.l"
{ return(TOKENIZER_TYPE); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 42 "golexer.l"
{ return(TOKENIZER_TYPE); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 44 "golexer.l"
{ return(TOKENIZER_KEYWORD); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 45 "golexer.l"
{ return(TOKENIZER_KEYWORD); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 46 "golexer.l"
{ return(TOKENIZER_KEYWORD); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 47 "golexer.l"
{ return(TOKENIZER_KEYWORD); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 48 "golexer.l"
{ return(TOKENIZER_KEYWORD); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 49 "golexer.l"
{ return(TOKENIZER_KEYWORD); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 50 "golexer.l"
{ return(TOKENIZER_KEYWORD); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 51 "golexer.l"
{ return(TOKENIZER_KEYWORD); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 52 "golexer.l"
{ return(TOKENIZER_KEYWORD); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 53 "golexer.l"
{ return(TOKENIZER_KEYWORD); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 54 "golexer.l"
{ return(TOKENIZER_KEYWORD); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 55 "golexer.l"
{ return(TOKENIZER_KEYWORD); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 56 "golexer.l"
{ return(TOKENIZER_KEYWORD); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 57 "golexer.l"
{ return(TOKENIZER_KEYWORD); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 58 "golexer.l"
{ return(TOKENIZER_KEYWORD); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 59 "golexer.l"
{ return(TOKENIZER_KEYWORD); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 60 "golexer.l"
{ return(TOKENIZER_KEYWORD); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 61 "golexer.l"
{ return(TOKENIZER_KEYWORD); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 62 "golexer.l"
{ return(TOKENIZER_KEYWORD); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 63 "golexer.l"
{ return(TOKENIZER_KEYWORD); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 64 "golexer.l"
{ return(TOKENIZER_KEYWORD); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 65 "golexer.l"
{ return(TOKENIZER_KEYWORD); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 67 "golexer.l"
{ BEGIN(comment); return(TOKENIZER_COMMENT); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 68 "golexer.l"
{ return(TOKENIZER_COMMENT); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 69 "golexer.l"
{ return(TOKENIZER_COMMENT); }
	YY_BREAK
case 49:
/* rule 49 can match eol */
YY_RULE_SETUP
#line 70 "golexer.l"
{ return(TOKENIZER_NEWLINE); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 71 "golexer.l"
{ return(TOKENIZER_NEWLINE); }
	YY_BREAK
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 72 "golexer.l"
{ return(TOKENIZER_NEWLINE); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 73 "golexer.l"
{ BEGIN(INITIAL); return(TOKENIZER_COMMENT); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 75 "golexer.l"
{ return(TOKENIZER_COMMENT); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 77 "golexer.l"
{ BEGIN(string_literal);    return(TOKENIZER_LITERAL); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 78 "golexer.l"
{ return(TOKENIZER_LITERAL); }
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 79 "golexer.l"
{ return(TOKENIZER_NEWLINE); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 80 "golexer.l"
{ return(TOKENIZER_NEWLINE); }
	YY_BREAK
case 58:
/* rule 58 can match eol */
YY_RULE_SETUP
#line 81 "golexer.l"
{ return(TOKENIZER_NEWLINE); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 82 "golexer.l"
{ BEGIN(INITIAL);           return(TOKENIZER_LITERAL); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 85 "golexer.l"
{ return(TOKENIZER_LITERAL); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 86 "golexer.l"
{ return(TOKENIZER_LITERAL); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 87 "golexer.l"
{ return(TOKENIZER_LITERAL); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 88 "golexer.l"
{ return(TOKENIZER_LITERAL); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 89 "golexer.l"
{ return(TOKENIZER_LITERAL); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 90 "golexer.l"
{ return(TOKENIZER_LITERAL); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 91 "golexer.l"
{ return(TOKENIZER_LITERAL); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 92 "golexer.l"
{ return(TOKENIZER_LITERAL); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 93 "golexer.l"
{ return(TOKENIZER_LITERAL); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 94 "golexer.l"
{ return(TOKENIZER_LITERAL); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 95 "golexer.l"
{ return(TOKENIZER_LITERAL); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 96 "golexer.l"
{ return(TOKENIZER_LITERAL); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 97 "golexer.l"
{ return(TOKENIZER_LITERAL); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 98 "golexer.l"
{ return(TOKENIZER_LITERAL); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 99 "golexer.l"
{ return(TOKENIZER_LITERAL); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 100 "golexer.l"
{ return(TOKENIZER_LITERAL); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 102 "golexer.l"
{ return(TOKENIZER_LITERAL); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 103 "golexer.l"
{ return(TOKENIZER_LITERAL); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 104 "golexer.l"
{ return(TOKENIZER_LITERAL); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 106 "golexer.l"
{ return(TOKENIZER_LITERAL); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 107 "golexer.l"
{ return(TOKENIZER_LITERAL); }
	YY_BREAK
case 81:
/* rule 81 can match eol */
YY_RULE_SETUP
#line 109 "golexer.l"
{ return(TOKENIZER_NEWLINE); }
	YY_BREAK
case 82:
/* rule 82 can match eol */
YY_RULE_SETUP
#line 110 "golexer.l"
{ return(TOKENIZER_NEWLINE); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 111 "golexer.l"
{ return(TOKENIZER_NEWLINE); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 112 "golexer.l"
{ return(TOKENIZER_TEXT);    }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 113 "golexer.l"
{ return(TOKENIZER_TEXT);    }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 114 "golexer.l"
{ return(TOKENIZER_TEXT);    }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 116 "golexer.l"
ECHO;
	YY_BREAK
#line 1492 "golexer.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(comment):
case YY_STATE_EOF(string_literal):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed go_in at a new source and called
			 * go_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = go_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( go_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * go_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of go_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					go_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			go_restart(go_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) go_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 241 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 241 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 240);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up go_text */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					go_restart(go_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( go_wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve go_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void go_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        go_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            go__create_buffer(go_in,YY_BUF_SIZE );
	}

	go__init_buffer(YY_CURRENT_BUFFER,input_file );
	go__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void go__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		go_pop_buffer_state();
	 *		go_push_buffer_state(new_buffer);
     */
	go_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	go__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (go_wrap()) processing, but the only time this flag
	 * is looked at is after go_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void go__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	go_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE go__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) go_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in go__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) go_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in go__create_buffer()" );

	b->yy_is_our_buffer = 1;

	go__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with go__create_buffer()
 * 
 */
    void go__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		go_free((void *) b->yy_ch_buf  );

	go_free((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a go_restart() or at EOF.
 */
    static void go__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	go__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then go__init_buffer was _probably_
     * called from go_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void go__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		go__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void go_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	go_ensure_buffer_stack();

	/* This block is copied from go__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from go__switch_to_buffer. */
	go__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void go_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	go__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		go__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void go_ensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)go_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in go_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)go_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in go_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE go__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) go_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in go__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	go__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to go_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       go__scan_bytes() instead.
 */
YY_BUFFER_STATE go__scan_string (yyconst char * yystr )
{
    
	return go__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to go_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE go__scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) go_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in go__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = go__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in go__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up go_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		go_text[go_leng] = (yy_hold_char); \
		(yy_c_buf_p) = go_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		go_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int go_get_lineno  (void)
{
        
    return go_lineno;
}

/** Get the input stream.
 * 
 */
FILE *go_get_in  (void)
{
        return go_in;
}

/** Get the output stream.
 * 
 */
FILE *go_get_out  (void)
{
        return go_out;
}

/** Get the length of the current token.
 * 
 */
int go_get_leng  (void)
{
        return go_leng;
}

/** Get the current token.
 * 
 */

char *go_get_text  (void)
{
        return go_text;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void go_set_lineno (int  line_number )
{
    
    go_lineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see go__switch_to_buffer
 */
void go_set_in (FILE *  in_str )
{
        go_in = in_str ;
}

void go_set_out (FILE *  out_str )
{
        go_out = out_str ;
}

int go_get_debug  (void)
{
        return go__flex_debug;
}

void go_set_debug (int  bdebug )
{
        go__flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from go_lex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    go_in = stdin;
    go_out = stdout;
#else
    go_in = (FILE *) 0;
    go_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * go_lex_init()
     */
    return 0;
}

/* go_lex_destroy is for both reentrant and non-reentrant scanners. */
int go_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		go__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		go_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	go_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * go_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *go_alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *go_realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void go_free (void * ptr )
{
	free( (char *) ptr );	/* see go_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 116 "golexer.l"



int go_wrap ( void ) {
	{
		/* Silly impossible function call to stop warning of unused functions */
		if ( 0 ) {
			yyunput(0, "");
		}
	}
    return 1;
}

