
<!-- Begin Footer -->

        <HR>

        <TABLE Width="100%">
        <TR>
          <TD Width="60%" Align=Center VAlign=Middle>
            <I>&copy;2002, 2003 CGDB development team.</i>
          </td>
          <TD Align=Right>
            <A Href="http://validator.w3.org/check/referer">
              <IMG Src="http://www.w3.org/Icons/valid-html401"
                   Width=88 Height=31 Border=0 Alt="Valid HTML 4.01!"></a>
          </td>
        </tr>
        </table>

      </td>
    </tr>
    </table>
  
  </td>
</tr>
</table>

</body>

</html>
