<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>

<!-- Header -->
<HEAD>
<TITLE>CGDB - a curses debugger</title>
<META Http-Equiv="Content-Type" Content="text/html; charset=us-ascii">
<META Name="keywords" Content="cgdb gdb debugger curses ncurses interface 
                               frontend front end console">
<LINK Rel=STYLESHEET Href="style.css" Type="text/css">
</head>

<BODY>

<TABLE Width="100%">
<TR>
  <TD ColSpan=2>

    <!-- Title -->
    <FONT Size="+2">CGDB</font><BR>
    <I>A curses debugger</i>
    <HR>

  </td>
</tr>
    
<TR>
  <TD Class=Menu VAlign=Top Width="18%">

    <!-- Link bar -->
    <A Href="index.shtml">Home</a><BR>
    <A Href="devel.shtml">Development</a><BR>
    <A Href="screenshots.shtml">Screenshots</a><BR>
    <A Href="download.shtml">Download</a><BR>
    <A Href="help.shtml">Help</a><BR>
    <A Href="contact.shtml">Contact</a><BR>
    <A Href="http://www.sourceforge.net/projects/cgdb">SourceForge Project</a><BR>
    <A Href="http://cvs.sourceforge.net/cgi-bin/viewcvs.cgi/cgdb/cgdb">CVS Browser</a><BR>

  </td>

  <TD>
    <TABLE Class=Main Width="100%">
    <TR>
      <TD>

<!-- End of Header -->

