name: C/C++ CI

on:
  push:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    if: >-
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./autogen.sh && ./configure
    - name: make
      run: make
